server:
  port: 9090

spring:
  application:
    name: opex-hub

  datasource:
    url: jdbc:oracle:thin:@172.16.14.54:1603:UAT5419C
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: APPS
    password: apps

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect  # Updated from Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

# Disable H2 console (since we're not using H2 now)
h2:
  console:
    enabled: false

security:
  user:
    name: admin
    password: admin

logging:
  level:
    com.company.opexhub: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: opexHubSecretKey2024ForJWT
  expiration: 86400000 # 24 hours

cors:
  allowed-origins: http://localhost:8080,http://localhost:5173,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
